import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import Navbar from "@/components/layout/Navbar";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bjoey Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Toaster />
        <main className="flex flex-col min-h-screen bg-gray-100">
        <Navbar />
          <section className="flex-grow">
            {children}
          </section>
        </main>
      </body>
    </html>
  </ClerkProvider>
  );
}
